[project]
name = "mmd-project"
version = "0.1.0"
description = "Mining Massive Datasets project, University of Verona (A.Y. 2024/2025)"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mypy>=1.16.1",
    "pre-commit>=4.2.0",
    "pytest>=8.4.1",
    "ruff>=0.12.1",
]
